steps:
- name: 'gcr.io/$PROJECT_ID/hugo'
- name: 'gcr.io/$PROJECT_ID/firebase'
  args: ['deploy']
  secretEnv: ['FIREBASE_TOKEN']
secrets:
- kmsKeyName: 'projects/quickstart-9b313/locations/global/keyRings/cloudbuilder/cryptoKeys/firebase-token'
  secretEnv:
    FIREBASE_TOKEN: 'CiQAROZiHGM8kCToU0G1jfKVMhLpkX4zIBoi4Y6XM/jipQo3EuISawCKyDGWkj+9a2AHEYPXBVY+gS08q4UbiwNekeCGbO7mumve7T9GkDn7AXQBabP4dnl+AGVx+GyEIKaHQ5okSFcefuxg0rzFKNIP0d2VGuWIss2uYpViF4CfPp7Jp0DeV/8yX75U0yuLLVeZ'
